name=U8glib
version=1.19.1
author=olikraus
maintainer=olikraus
sentence=Universal 8bit Graphics Library
paragraph=Legacy U8glib for Marlin 1.1.x
category=Display
url=https://github.com/olikraus/u8glib
architectures=*
